### ISSUE TITLE
KeyError: 'r_addend' on Ubuntu 14.04 Python3.4.3

### ISSUE THREAD

**Issue by sheinz** [pfalcon/ScratchABit#11] opened 2016-06-29 14:14 UTC
Hi,

I'm having trouble running ScratchABit on my machine:

```
$ python scratchabit.py example-elf
Traceback (most recent call last):
  File "scratchabit.py", line 721, in <module>
    load_target_file(loader, sys.argv[1])
  File "scratchabit.py", line 623, in load_target_file
    entry = loader.load(engine.ADDRESS_SPACE, fname)
  File "/home/user/esp/virtenv/ScratchABit/plugins/loader/elf.py", line 407, in load
    return load_sections(aspace, elffile)
  File "/home/user/esp/virtenv/ScratchABit/plugins/loader/elf.py", line 280, in load_sections
    if reloc["r_addend"] != 0:
  File "/home/user/esp/virtenv/ScratchABit/plugins/loader/pyelftools/elftools/elf/relocation.py", line 35, in __getitem__
    return self.entry[name]
  File "/home/user/esp/virtenv/ScratchABit/plugins/loader/pyelftools/elftools/construct/lib/container.py", line 35, in __getitem__
    return self.__dict__[name]
KeyError: 'r_addend'
```

Am I missing something?
I use Ubuntu 14.04 with Python 3.4.3
Thanks

**Comment by BlueShrub** [comment] 2016-07-02 19:52
Same issue here

```
$ uname -a
Linux novi-ThinkPad-X120e 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ python3 -V
Python 3.4.3+

$ python3 scratchabit.py example-elf
Traceback (most recent call last):
  File "scratchabit.py", line 721, in <module>
    load_target_file(loader, sys.argv[1])
  File "scratchabit.py", line 623, in load_target_file
    entry = loader.load(engine.ADDRESS_SPACE, fname)
  File "/opt/ScratchABit/plugins/loader/elf.py", line 407, in load
    return load_sections(aspace, elffile)
  File "/opt/ScratchABit/plugins/loader/elf.py", line 280, in load_sections
    if reloc["r_addend"] != 0:
  File "/opt/ScratchABit/plugins/loader/pyelftools/elftools/elf/relocation.py", line 35, in __getitem__
    return self.entry[name]
  File "/opt/ScratchABit/plugins/loader/pyelftools/elftools/construct/lib/container.py", line 35, in __getitem__
    return self.__dict__[name]
KeyError: 'r_addend'
```

**Comment by pfalcon** [comment] 2016-07-02 20:18
Thanks for the reports, confirmed.

**Comment by pfalcon** [comment] 2016-07-02 21:47
Partial fix was pushed, though it still crashes later. The issue is that recently "advanced" loading of Xtensa ELF files was added, which was implemented in an adhoc way and now clashes with x86. I'm on it.

**Comment by BlueShrub** [comment] 2016-07-02 22:00
That's a pretty solid response time :).

In the event it's helpful, this is the new error on my machine (although I imagine it's what you were referring to):

```
# python3 scratchabit.py example-elf
Traceback (most recent call last):
  File "scratchabit.py", line 721, in <module>
    load_target_file(loader, sys.argv[1])
  File "scratchabit.py", line 623, in load_target_file
    entry = loader.load(engine.ADDRESS_SPACE, fname)
  File "/opt/ScratchABit/plugins/loader/elf.py", line 409, in load
    return load_sections(aspace, elffile)
  File "/opt/ScratchABit/plugins/loader/elf.py", line 296, in load_sections
    rel_type = RELOC_TYPES[reloc["r_info_type"]]
KeyError: 7

```

**Comment by pfalcon** [comment] 2016-07-03 10:32
Yes, that was the other error, and it's now fixed too. `python scratchabit.py example-elf` now works as expected.

**Closed as completed by pfalcon** 2016-07-03 10:32 UTC

**Comment by BlueShrub** [comment] 2016-07-03 17:43
Works for me now.  My first time using this tool -- pretty handy!  Very impressed.

Thanks again!

**Comment by pfalcon** [comment] 2016-07-03 22:16
You're welcome. And I know it could be made better, and that's on todo ;-).
